# https://syncpack.dev/config/sort-first/
sortFirst:
  - name
  - version
  - private
  - type
  - sideEffects
  - exports
  - files
  - scripts
  - dependencies
  - devDependencies
  - peerDependencies
  - optionalDependencies

# https://syncpack.dev/version-groups/
versionGroups:
  - label: "`workspace:*` packages"
    pinVersion: "workspace:*"
    dependencies:
      - "@navifox/*"

  - label: "`catalog:` packages"
    pinVersion: "catalog:"
    dependencies:
      - "@iconify/vue"
      - "@tailwindcss/vite"
      - "@types/markdown-it"
      - "@types/node"
      - "@unhead/vue"
      - "@vitejs/plugin-vue"
      - "@vue/tsconfig"
      - "@vueuse/core"
      - "class-variance-authority"
      - "clsx"
      - "es-toolkit"
      - "gsap"
      - "markdown-it"
      - "reka-ui"
      - "tailwindcss"
      - "tailwind-merge"
      - "tw-animate-css"
      - "typescript"
      - "uuid"
      - "vite"
      - "vite-plugin-zip-file"
      - "vue"
      - "vue-router"
      - "vue-tsc"

  - label: "Ignored version packages"
    isIgnored: true
    dependencies:
      - "genshin-db"
